apiVersion: apps/v1
kind: Deployment #Service job
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-node
          image: kavyacd/kub-first-app
        #- name: second-node
        #  image: kavyacd/kub-first-app:2
