apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kavyacd/kub_demo_user:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default" # name of the auth service as mentioned in auth-service
