apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node
    # - ReadWriteMany # The volume can be mounted as read-write by many nodes simultaneously
    # - ReadOnlyMany # The volume can be mounted as read-only by many nodes simultaneously
  hostPath:
    path: /data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv #name of the volume that needs to be claimed
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
